### ISSUE TITLE
Undefined portmidi.DeviceId and portmidi.GetDefaultInputDeviceId on new install

### ISSUE THREAD

**Issue by elkelk** [nf/sigourney#14]
Just followed the install instructions:

``` bash
brew update
brew install portaudio portmidi
go get -u github.com/nf/sigourney
>> # github.com/nf/sigourney/midi
>> midi/midi_cgo.go:29: undefined: portmidi.DeviceId
>> midi/midi_cgo.go:31: undefined: portmidi.GetDefaultInputDeviceId
```

Looking at the [portmidi](https://github.com/rakyll/portmidi) repo it appears that the API has similar methods:

```
portmidi.DeviceInfo(deviceId) // returns info about a MIDI device
portmidi.DefaultInputDeviceID() // returns the ID of the system default input
```

Does the portmidi interaction need to be updated or am I just missing something?

(I'm running go version go1.5.3 darwin/amd64)

**Comment by ei-grad** [comment]
Same for me on linux.

**Comment by nf** [comment]
Just closed an issue that should fix this.
